### ISSUE TITLE
Move documentation to Cloudflare Pages

### ISSUE THREAD

**Issue by tomodwyer** [opensafely/documentation#237]
So that we can build a version of the site on each PR and easily preview changes.

- [x] Set up repo on Cloudflare Pages
- [x] Set up redirects on Cloudflare Pages (https://github.com/opensafely/documentation/pull/238)
- [x] Switch DNS
- [x] Set up Cloudflare redirects at DNS-level
- [x] Remove readthedocs site
- [x] ~Remove GitHub Actions~  
Ignored for the moment, see discussion below
- [ ] Add Plausible Analytics (https://github.com/opensafely/documentation/pull/241)

**Comment by StevenMaude** [comment]
> Remove GitHub Actions

:thought_balloon: I have a comment rather than too strong an opinion: *people without Cloudflare access can't see why a build fails*. I'm not sure whether this is too big a deal though.

If you clone locally and work there you can always check the build yourself. But for someone just editing on GitHub, if they accidentally break something, there's no obvious way for them to see it's broken. They would just get a "no" from Cloudflare :x:

Also, if it's somebody's own fork, then there won't be any checks on changes at all as the Cloudflare build won't run for them. However, I'm not entirely sure if we having the slight duplication of the GitHub build check is beneficial or not. So, interested to see what people think.
 
---

While I'm here, and on a similar topic, I'll suggest `mkdocs build --strict` for the site build if you haven't already considered that @tomodwyer. Unless there are sensible reasons not to do this (e.g. we actually do want to ignore some warnings). I picked up a few broken things previously due to this, and it's probably better to catch them before merging.

**Comment by tomodwyer** [comment]
@StevenMaude 

> If you clone locally and work there you can always check the build yourself. But for someone just editing on GitHub, if they accidentally break something, there's no obvious way for them to see it's broken. They would just get a "no" from Cloudflare ❌
> 
> Also, if it's somebody's own fork, then there won't be any checks on changes at all as the Cloudflare build won't run for them. However, I'm not entirely sure if we having the slight duplication of the GitHub build check is beneficial or not. So, interested to see what people think.

Good point 🤔 I don't have any strong feelings one way or the other. I could amend this task to remove the deployment step from readthedocs, but keep the GitHub Action?

The other thing to consider is the extra cost of running the Actions alongside the Cloudflare Pages build, but I can't imagine the minutes used here are adding up to a high cost.

> While I'm here, and on a similar topic, I'll suggest `mkdocs build --strict` for the site build if you haven't already considered that @tomodwyer. Unless there are sensible reasons not to do this (e.g. we actually do want to ignore some warnings). I picked up a few broken things previously due to this, and it's probably better to catch them before merging.

That is fine, I brought that over from the GitHub Actions so we are using the strict mode with Cloudflare Pages.

**Comment by evansd** [comment]
> The other thing to consider is the extra cost of running the Actions alongside the Cloudflare Pages build, but I can't imagine the minutes used here are adding up to a high cost.

Actions _should_ be free as its a public repo.
