### ISSUE TITLE
🔗 rendering as `&#128279;`

### ISSUE THREAD

**Issue by Jongmassey** [opensafely/documentation#341]
Chrome 92.0.4515.10 on Win10 Build 19043.1110

 🔗 renders as as `&#128279;`  on the [variable reference page](https://docs.opensafely.org/study-def-variables/) on `h2`-level headings

**Comment by madwort** [comment]
also for me on Firefox / macOS

<img width="662" alt="Screenshot 2021-07-25 at 11 51 23" src="https://user-images.githubusercontent.com/2082895/126896531-5c37c04d-9a4e-4e27-a150-025cb734f096.png">

**Comment by StevenMaude** [comment]
Same here on Ubuntu.

So there's a fair amount of interaction here. Not sure what's to blame.

* The permanent link is configured by the [toc markdown extension](https://github.com/opensafely/documentation/blob/4ca91dd7d69fc0731f64524bf497cccdebf218dc/mkdocs.yml#L116).
* The docstrings are configured by mkdocstrings.
* It's not directly a font issue, I don't think, because you can replace the HTML entity with the link icon and have it display.
