### ISSUE TITLE
Give some intro text explaining what "measures" are, conceptually

### ISSUE THREAD

**Issue by sebbacon** [opensafely/documentation#35]
At https://docs.opensafely.org/en/latest/measures/

**Comment by wjchulme** [comment]
I've rewritten with an introduction and a more sensible example. It's mainly in this PR https://github.com/opensafely/documentation/pull/54 but have since improved (should've put it in one PR and waited for proper review). Best just to view the url above to read. 

Can reopen if you want further improvements.
