### ISSUE TITLE
Upgrade this repository to newer Python

### ISSUE THREAD

**Issue by StevenMaude** [opensafely/documentation#493]
This runs with ~Python 3.7~ Python 3.8, which is only getting security fixes now.

It also may have impact if we need to import the new cohort-extractor, which is only tested with Python 3.9.

Update: this is also a bit of a clunky usability issue, because you need:
* Python 3.7 to build or serve the content in this repository locally
* Python 3.10 for generating some content related to Data Builder

**Comment by ghickman** [comment]
IIRC this is because cohortextractor (v1) has a requirement on 3.7.

@evansd or @bloodearnest might remember where the 3.7 requirement came from?

**Comment by evansd** [comment]
cohortextractor-v1 actually runs against [3.8](https://github.com/opensafely-core/cohort-extractor/blob/1be28f4c9c8e05f5c08374f060db34ed2aa0bf9d/Dockerfile#L6). I don't think there's any reason not to upgrade this repo.

In terms of version compatibility the only thing which runs on a platform we don't control is [opensafely-cli](https://github.com/opensafely-core/opensafely-cli) and (purely because the CLI tool vendors it) [job-runner](https://github.com/opensafely-core/job-runner). Historically we've said that these need to be 3.7 compatible because, at the time, that's all some researchers had easy access to. It's probably past time to revist that policy. But in any case, we test on more recent versions too so there's no reason to keep the docs repo on an old version.

**Comment by StevenMaude** [comment]
Ah, what a lovely, naive thought I had :laughing:

After trial, error and then searching around, it seems that the latest Python in Cloudflare Pages is Python 3.7 (which is turn is based on a Netlify repository).

Maybe Docker's an undocumented option for the build, though I can't find *anything* on the internet, referring to use of Pages with Docker.

**Comment by StevenMaude** [comment]
Thanks to @tomodwyer, we switched the documentation site to use Render instead of Cloudflare Pages temporarily. This is until Cloudflare Pages add support for newer Python versions.

That change means we can move to at least Python 3.8 for the documentation site, so I've opened #651 which moves us to Python 3.8.

Ways to address this issue more comprehensively:

* ensure cohort-extractor, Data Builder and this repository all work with the same Python version
* remove the dependency of this repository on installing cohort-extractor and Data Builder, so that we only need install the MkDocs-related tooling
