### ISSUE TITLE
Change wording to not require private repositories, and encourage them

### ISSUE THREAD

**Issue by bloodearnest** [opensafely/documentation#864]
The current documentation for creating new repositories says to make it private, and there are various other assumptions of private repositories throughout the docs.

We should change the docs to default to public repositories, with an option for private if required (with associated open after 12 months policy).

**Comment by StevenMaude** [comment]
It might be worth explaining some of the motivations here too: *why is open code by default our suggested policy?*

**Comment by bloodearnest** [comment]
We should probably just link to https://docs.opensafely.org/open-data-manifesto/ for that?

**Comment by StevenMaude** [comment]
> We should probably just link to https://docs.opensafely.org/open-data-manifesto/ for that?

Yep; that's sufficient, I think :+1:

**Comment by CLStables** [comment]
Further info:
- Amir has confirmed he is fine with encouraging people to make their repos open from the start, as long as there is an option to keep them private and that if they are open by default THIS IS REALLY CLEAR TO RESEARCHERS so there is no way they could claim they didn’t realise/we didn’t tell them
- About page may need updating https://www.opensafely.org/about/
- Text in the DAA may need updating - 9b in [Canonical: Data Access Agreement for OpenSAFELY NHS England COVID-19 Research Platform](https://docs.google.com/document/d/1Kf8vL1Gy8t_AJgTTOcPtwl1vlBNQSCu855Bd4JUoL9I/edit)

**Comment by CLStables** [comment]
I think this issue probably needs some more refinement. If someone wants to pick it up before we've managed to refine it then please chat to me to make sure we are aligned on our understanding of what needs to be done - thanks!

Some thoughts:
- An early task should probably be to search through the onboarding process/documentation for all references to private repositories/making them public, so that we can consider the whole picture before choosing what to edit vs. delete/rearrange
- One of the acceptance criteria (before making live) should probably be for Amir to review the new content?
- Another acceptance criteria could be to have communicated the change to all current users (both internal and external) - do we have any sort of policy on how we do these comms? (I think Iain and the data team were grappling with this recently - may be worth checking with them for advice?)

**Comment by lucyb** [comment]
This is superseded by https://github.com/opensafely/documentation/issues/892
